ask:
  model: "intfloat/multilingual-e5-large-instruct" # NbAiLab/nb-bert-large"
  db_directory: "./chroma_db"
  conversation: true
  llm_model: "llama3.2"
  llm_base_url: "http://localhost:11434"
  llm_timeout: 300
  context_window: 3090
  verbose: false
  llm_max_tokens: 1024
  llm_temperature: 0.3
  llm_top_p: 0.1
  n_results: 5
  num_gpu: 1

colors:
  question_text: "green"
  answer_text: "blue"

prompts:
  default: |
    Based on the following context and conversation history, please answer the question:

    Context:
    {context}

    {conversation_history}
    Question: {query}

    Answer:

  concise: |
    Given this context:

    Context:
    {context}

    {conversation_history}
    Question: {query}

    Answer:

  detailed: |
    Analyze the following information:

    Context:
    {context}

    Provide a detailed answer to this question

    {conversation_history}
    Question: {query}

    Answer:
