read-documents:
  model_name: "intfloat/multilingual-e5-large-instruct" # NbAiLab/nb-bert-large"
  directory: "./documents"
  db_directory: "./chroma_db"
  chunk_size: 1024
  chunk_overlap: 20

ask:
  model: "intfloat/multilingual-e5-large-instruct" # NbAiLab/nb-bert-large"
  db_directory: "./chroma_db"
  conversation: true
  llm_model: "llama3.2"
  llm_base_url: "http://localhost:11434"
  llm_timeout: 300
  context_window: 3090
  verbose: false
  llm_max_tokens: 1024
  llm_temperature: 0.3
  llm_top_p: 0.1
  n_results: 100
  num_gpu: 1
  filter_similarities: true
  similarity_threshold: 0.5
  rerank_documents: true
  reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  rerank_top_k: 10
  colors:
  question_text: "green"
  answer_text: "blue"

prompts:
  default: |
    Based on the following context and conversation history, please answer the question:

    Context:
    {context}

    {conversation_history}
    Question: {query}

    Answer:

  concise: |
    Given this context:

    Context:
    {context}

    {conversation_history}
    Question: {query}

    Answer:

  detailed: |
    Analyze the following information:

    Context:
    {context}

    Provide a detailed answer to this question

    {conversation_history}
    Question: {query}

    Answer:
